Repository keshavsingh4522/hacktoberfest2021, pull requests merged in 2020-10, with the labels that each got.

#34 Please approve PR
  Python/sniff-all.py
  README.md
Labels: hacktoberfest-accepted

#35 Revert "Please approve PR"
  Python/sniff-all.py
  README.md
Labels: hacktoberfest-accepted

#36 multiplication_table.cpp
  CPP/a.out
  CPP/multiplication_table.cpp
  README.md
Labels: hacktoberfest-accepted

#37 Added Python program and name under participants
  Python/ListElements.py
  README.md
Labels: hacktoberfest-accepted

#38 contributed code in CPP
  CPP/pointers.cpp
  README.md
Labels: hacktoberfest-accepted

#41 updated readme and added a simple bet game
  Python/betgame.py
  README.md
Labels: hacktoberfest-accepted

#42 Create Comment.cpp
  CPP/Comment.cpp
Labels: hacktoberfest-accepted

#44 Arigato
  CPP/guess your number.cpp
  README.md
Labels: hacktoberfest-accepted

#46 Bubble sort in python
  Python/bubble_sort.py
Labels: first-time-contributer, hacktoberfest-accepted

#47 Creates count_sort.py
  Python/Created count_Sort.py
  README.md
Labels: first-time-contributer, hacktoberfest-accepted

#49 new code added
  CPP/gcd.cpp
  CPP/seive.cpp
Labels: first-time-contributer, hacktoberfest-accepted

#45 Muhammad Bilal added in Python
  Python/Dice Rolling by Muhammad Bilal.py
  README.md
Labels: hacktoberfest-accepted

#51 Added qrcode_generator.py
  Python/qrcode_generator.py
Labels: hacktoberfest-accepted

#50 created find the percentage.py
  Python/find the percentage.py
Labels: hacktoberfest-accepted

#52 Update README.md
  README.md
Labels: hacktoberfest-accepted

#53 Electron
  CPP/fifo.cpp
  README.md
Labels: first-time-contributer, hacktoberfest-accepted

#57 Find the repeating longest subsequence in a string
  DP/longestrepeatingsubsequence.cpp
  longestrepeatingsubsequence.cpp
Labels: first-time-contributer, hacktoberfest-accepted

#58 📝 C program to find frequency of numbers in an array
  C/frequencyOfDigits.c
  README.md
Labels: first-time-contributer, hacktoberfest-accepted

#59 printing shortest common super sequence print
  shortestcommonsupersequenceprint.cpp
Labels: first-time-contributer, hacktoberfest-accepted

#60 Apples datasets
  Python/data.txt
  Python/mwi00174_ECA.py
Labels: first-time-contributer, hacktoberfest-accepted

#61 added python programs
  Python/Anti_palindrome_strings.py
  Python/aSubsetInASequence.py
Labels: first-time-contributer, hacktoberfest-accepted

#62 Blog Website Code
  Assets/HTML5/indexWebsite.html
Labels: first-time-contributer, hacktoberfest-accepted

#63 Added bellman ford algorithm to cpp folder
  CPP/bellmanford.cpp
Labels: first-time-contributer, hacktoberfest-accepted

#64 Create xor_two_pictures.py
  Python/xor_two_pictures.py
Labels: first-time-contributer, hacktoberfest-accepted

#68 Keshav
  CONTRIBUTING.md
  README.md
Labels: hacktoberfest-accepted

#65 Added djikstra algorithm to the cpp folder
  CPP/DetectCycleUnionFind.cpp
  CPP/djikstra.cpp
Labels: hacktoberfest-accepted

#69 Create Snake_with_ladder.py
  Python/Snake_with_ladder.py
Labels: first-time-contributer, hacktoberfest-accepted

#70 Create GUI_sorting.py
  Python/GUI_sorting.py
Labels: hacktoberfest-accepted

#67 Update README.md
  README.md
Labels: first-time-contributer, hacktoberfest-accepted

#73 added new python programs
  Python/array_duplicates.py
  Python/equal_subarrays.py
Labels: first-time-contributer, hacktoberfest-accepted

#74 changed inner loop structure
  C/frequencyOfDigits.c
Labels: first-time-contributer, hacktoberfest-accepted

#75 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: first-time-contributer, hacktoberfest-accepted

#77 Text to speech GUI in python
  CONTRIBUTING.md
  Python/Text-to-Speech/required.bat
  Python/Text-to-Speech/sqpy.png
  Python/Text-to-Speech/tts.py
Labels: first-time-contributer, hacktoberfest-accepted

#79 Added To-do App in JS
  CONTRIBUTING.md
  JS/To-do app/fonts/Jost-Italic-VariableFont_wght.ttf
  JS/To-do app/fonts/Jost-VariableFont_wght.ttf
  JS/To-do app/fonts/PROPAGAN.ttf
  JS/To-do app/fonts/akaPosse.ttf
  JS/To-do app/fresh.js
  JS/To-do app/index.html
  JS/To-do app/style.css
Labels: hacktoberfest-accepted

#78 2players-Tic Tac Toe game in Python
  Python/Discord_bot_python.py
  Python/tictactoe_tkinter.py
Labels: hacktoberfest-accepted

#80 Discord_bot_for_programmers.py
  Python/Discord_bot_for_programmers.py
Labels: hacktoberfest-accepted

#83 HEX to RGB in Python
  JS/To-do app/style.css
  Python/hex_to_rgb.py
  Python/random_walk.py
Labels: hacktoberfest-accepted

#82 update Contribution.md
  CONTRIBUTING.md
Labels: first-time-contributer, hacktoberfest-accepted

#71 fixed username
  README.md
Labels: hacktoberfest-accepted

#85 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: first-time-contributer, hacktoberfest-accepted

#86 Keshav
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: hacktoberfest-accepted

#84 Leap Year Program
  leapyear.py
Labels: hacktoberfest-accepted

#87 Added linear search code with comments
  .DS_Store
  .idea/.gitignore
  .idea/hacktoberfest2020-2.iml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  Python/LinearSearch.py
Labels: first-time-contributer, hacktoberfest-accepted

#88 Prims Algorithm
  Prims Algorithm
Labels: first-time-contributer, hacktoberfest-accepted

#90 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: first-time-contributer, hacktoberfest-accepted

#91 Palindrome Partition
  CONTRIBUTING.md
  Python/palindrome_partition.py
Labels: first-time-contributer, hacktoberfest-accepted

#92 Create pc_health_check.py
  pc_health_check.py
Labels: first-time-contributer, hacktoberfest-accepted

#93 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: first-time-contributer, hacktoberfest-accepted

#95 added Dijkstra’s in c
  C/dijkstra_s .c
  CONTRIBUTING.md
Labels: first-time-contributer, hacktoberfest-accepted

#96 AbuBakar Sheikh
  CONTRIBUTING.md
Labels: first-time-contributer, hacktoberfest-accepted

#97 Keshav
  CONTRIBUTERS.MD
  CONTRIBUTING.md
  README.md
Labels: hacktoberfest-accepted

#98 Update even or odd.py
  Python/even or odd.py
Labels: first-time-contributer, hacktoberfest-accepted

#94 Create TowerofHanoi.cpp
  CPP/TowerofHanoi.cpp
Labels: first-time-contributer, hacktoberfest-accepted

#89 Create FaceDetectorWithFaceRecognition
  Python/FaceDetectorWithFaceRecognition
Labels: first-time-contributer, hacktoberfest-accepted

#100 Create Binary_Search.c
  C/Binary_Search.c
Labels: first-time-contributer, hacktoberfest-accepted

#101 Keshav
  .github/PULL_REQUEST_TEMPLATE.md
Labels: hacktoberfest-accepted

#103 created road lines detector
  Python/RoadLineDetector/RoadLineDetector.py
  Python/RoadLineDetector/roads.jpg
Labels: first-time-contributer, hacktoberfest-accepted

#107 Facial regonition with keras
  camera.py
Labels: hacktoberfest-accepted

#106 CONTRIBUTERS added
  README.md
Labels: hacktoberfest-accepted

#108 RockPaperScissors.py
  Python/RockPaperScissors.py
Labels: first-time-contributer, hacktoberfest-accepted

#111 Updated CONTRIBUTERS.MD
  CONTRIBUTERS.MD
  Python/compress_string.py
Labels: first-time-contributer, hacktoberfest-accepted

#112 Instagram HD
  CONTRIBUTERS.MD
  Python/Instagram HD/InstagramHD.py
  Python/Instagram HD/README.md
Labels: first-time-contributer, hacktoberfest-accepted

#113 Update CONTRIBUTERS.MD
  CONTRIBUTERS.MD
Labels: first-time-contributer, hacktoberfest-accepted

#109 armstrongnumber.cpp
  CONTRIBUTERS.MD
  CPP/armstrongnumber.cpp
Labels: first-time-contributer, hacktoberfest-accepted

#116 Keshav
  CONTRIBUTERS.MD
  CONTRIBUTERS.csv
  README.md
Labels: hacktoberfest-accepted

#117 fixed encode utf-8 error
  README.md
Labels: hacktoberfest-accepted

#120 Added PyFiglet
  Python/PyFiglet/PyFiglet.py
  Python/PyFiglet/README.md
Labels: hacktoberfest-accepted

#121 Update CONTRIBUTERS.MD
  CONTRIBUTERS.MD
Labels: firrst-pull-request, hacktoberfest-accepted

#122 Create Stack.py
  Python/Stack.py
Labels: firrst-pull-request, hacktoberfest-accepted

#123 roll the dice in python
  CONTRIBUTERS.MD
  Python/roll_the_dice.py
Labels: firrst-pull-request, hacktoberfest-accepted

#114 simple even and odd.py
  Python/even or odd.py
Labels: first-time-contributer, hacktoberfest-accepted

#115 Create BubbleSort.java
  BubbleSort.java
Labels: first-time-contributer, hacktoberfest-accepted

#118 Adding code for truthanddare
  Python/truthordare.py
Labels: first-time-contributer, hacktoberfest-accepted

#124 Create DataFlair-Alarm-Clock.py
  Python/DataFlair-Alarm-Clock.py
Labels: firrst-pull-request, first-time-contributer, hacktoberfest-accepted

#125 contributers
  CONTRIBUTERS.csv
  README.md
Labels: hacktoberfest-accepted

#127 corrected code
  leapyear.py
Labels: firrst-pull-request, hacktoberfest-accepted

#128 Sparse Matrix Erase using C
  C/Sparse Matrix.c
Labels: hacktoberfest-accepted

#129 C Program to perform 3 sort operations
  C/Menu Driven Sorting Algo.c
Labels: hacktoberfest-accepted

#131 Circular Queue Operations Using C
  C/Circular Queue.c
  CONTRIBUTERS.MD
Labels: hacktoberfest-accepted

#130 added quicksort (divide - conquer approach)
  quicksort.py
Labels: hacktoberfest-accepted

#132 Doubly Linked List in C
  C/Doubly Linked List.c
Labels: hacktoberfest-accepted

#134 🚀 contributers
  CONTRIBUTERS.csv
  README.md
Labels: hacktoberfest-accepted

#135 Created Rabin_Karp.py
  Python/Rabin_Karp.py
Labels: hacktoberfest-accepted

#136 simple python Code for diversified portfolio
  Diversified_Portfolio.py
Labels: hacktoberfest-accepted

#138 Create Screenshot_using_python.py
  Python/Screenshot_using_python.py
Labels: hacktoberfest-accepted

#137 Create sum_of_two_numbers.py
  Python/sum_of_two_numbers.py
Labels: hacktoberfest-accepted

#139 Update even or odd.py
  Python/even or odd.py
Labels: hacktoberfest-accepted

#143 Windows Wifi Passwords Extractor
  CONTRIBUTERS.MD
  CPP/win_wifi_pass_extract.cpp
Labels: hacktoberfest-accepted

#144 🚀 contributers
  CONTRIBUTERS.csv
  README.md
Labels: hacktoberfest-accepted

#145 Update CONTRIBUTERS.MD
  CONTRIBUTERS.MD
Labels: hacktoberfest-accepted

#147 print of a number using python
  CONTRIBUTERS.MD
  Python/comparison _of_ two_ numbers_ to_ find_the_largest
  Python/print_number
  Python/square_area.py
  Python/transform_meters_to_centimeters.py
  sum_and_arithmetic_average_of_20_numbers
Labels: hacktoberfest-accepted

#151 Update CONTRIBUTERS.MD
  CONTRIBUTERS.MD
Labels: hacktoberfest-accepted

#150 Create Digital Clock,c
  Digital Clock,c
Labels: hacktoberfest-accepted

#152 Squareroot.py
  CONTRIBUTERS.MD
  Python/squareroot.py
Labels: hacktoberfest-accepted

#153 Added Instagram Hashtag
  Python/Instagram Hashtag/Instagram.py
  Python/Instagram Hashtag/README.md
Labels: hacktoberfest-accepted

#154 🚀 contributers
  CONTRIBUTERS.csv
  README.md
Labels: hacktoberfest-accepted

#158 Change EventCenter.cs
  C#/EventCenter.cs
  C#/PlayerDeathDetectSystem.cs
Labels: hacktoberfest-accepted

#165 Added selection_sort.py
  Python/selection_sort.py
Labels: hacktoberfest-accepted

#166 Added Quicksort, Mergesort, Heap Codes
  CONTRIBUTERS.MD
  CPP/heap.cpp
  CPP/merge_sort.cpp
  CPP/quicksort.cpp
Labels: hacktoberfest-accepted

#167 Keshav
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTERS.MD
  CONTRIBUTERS.csv
  README.md
Labels: hacktoberfest-accepted

#176 🌟 contributers added
  CONTRIBUTERS.MD
  CONTRIBUTERS.csv
  README.md
  result.md
Labels: hacktoberfest-accepted

#177 Added bucket sort
  CONTRIBUTERS.MD
  Java/BucketSort.java
Labels: hacktoberfest-accepted

#178 🌟 contributers added
  CONTRIBUTERS.csv
  README.md
  result.md
Labels: hacktoberfest-accepted

#179 :open_file_folder: Assets folder added
  Assets/Hacktoberfest_20.png
  Assets/SponsorsDarkBoxed.svg
  Assets/hacktober-logo.svg
Labels: hacktoberfest-accepted

#162 Add Postfix.c
  C/postfix.c
Labels: hacktoberfest-accepted

#184 🚀 contributers added
  CONTRIBUTERS.MD
  CONTRIBUTERS.csv
  README.md
  result.md
  script.py
Labels: hacktoberfest-accepted

#183 Reversing Number in c++
  CPP/reversingNumber.cpp
Labels: hacktoberfest-accepted

#185 adding name
  CONTRIBUTERS.MD
  Python/xmas.py
Labels: hacktoberfest-accepted

#186 🚀 contributers added
  CONTRIBUTERS.csv
  README.md
  result.md
Labels: hacktoberfest-accepted

#187 Update CONTRIBUTERS.MD
  CONTRIBUTERS.MD
Labels: hacktoberfest-accepted

#189 🚀 contributers added
  CONTRIBUTERS.csv
  README.md
  result.md
Labels: hacktoberfest-accepted

#188 Create Add_Group
  Java/Add_Group.java
Labels: hacktoberfest-accepted

#192 Longest Increasing and Decreasing Subsequence program added under DP Directory
  DP/longest_increasing_and_decreasing_subsequence.cpp
Labels: hacktoberfest-accepted

#194 Added PeakElement.cpp
  CONTRIBUTERS.MD
  CPP/PeakElement.cpp
Labels: hacktoberfest-accepted

#196 Update CONTRIBUTERS.MD
  CONTRIBUTERS.MD
Labels: hacktoberfest-accepted

#198 Selection sorting in JS
  CONTRIBUTERS.MD
  JS/selectionSorting.js
Labels: hacktoberfest-accepted

#199 🚀 contributers added
  CONTRIBUTERS.csv
  README.md
  result.md
Labels: hacktoberfest-accepted

#201 Keshav
  README.md
  result.md
  script.py
Labels: hacktoberfest-accepted

#205 Update CONTRIBUTERS.MD
  CONTRIBUTERS.MD
Labels: hacktoberfest-accepted

#202 Update CONTRIBUTERS.MD
  CONTRIBUTERS.MD
Labels: hacktoberfest-accepted

#206 🚀 contributers added
  CONTRIBUTERS.csv
  README.md
  result.md
Labels: hacktoberfest-accepted

#207 Add files via upload
  CONTRIBUTERS.MD
  CPP/Alternating Characters.cpp
  Java/Union2Arrays.java
Labels: hacktoberfest-accepted

#210 Created fibonaccisequence.py
  CONTRIBUTERS.MD
  Python/fibonaccisequence.py
  fibonacci-sequence.py
Labels: hacktoberfest-accepted

#211 Keshav
  CONTRIBUTERS.MD
  CONTRIBUTERS.csv
  Python/fibonacci-sequence.py
  README.md
  result.md
Labels: hacktoberfest-accepted

#208 Create Port_Scanner.py
  Python/Port_Scanner.py
Labels: hacktoberfest-accepted

#212 Shoom1337
  CONTRIBUTERS.MD
  JS/iOS8 calculator/README.txt
  JS/iOS8 calculator/css/style.css
  JS/iOS8 calculator/index.html
  JS/iOS8 calculator/js/index.js
  JS/iOS8 calculator/license.txt
Labels: hacktoberfest-accepted

#215 🚀 Contributers added
  CONTRIBUTERS.csv
  README.md
  result.md
Labels: hacktoberfest-accepted

#218 Update CONTRIBUTERS.MD
  CONTRIBUTERS.MD
Labels: hacktoberfest-accepted

#227 Cpp code to convert a postfix expression using STL
  CPP/Stack2postfix.cpp
Labels: hacktoberfest-accepted

#229 Add files via upload
  Python/tcs nqt dr consultation.py
Labels: hacktoberfest-accepted

#232 Create simpleinterest.py
  Python/simpleinterest.py
Labels: hacktoberfest-accepted

#233 🚀 Contributers added
  CONTRIBUTERS.csv
  README.md
  result.md
Labels: hacktoberfest-accepted

#236 Create dec2bin.py
  Python/dec2bin.py
Labels: hacktoberfest-accepted

#240 Added bucket sort in c#
  C#/BucketSort.cs
Labels: hacktoberfest-accepted

#242 Create listopera.py
  Python/listopera.py
Labels: hacktoberfest-accepted

#243 Create slice.py
  Python/slice.py
Labels: hacktoberfest-accepted
